---
title: "Non-Compliance/Exit Analysis"
author: "Monica Chang"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(gt)
library(readxl)
library(lubridate)
library(skimr)
library(janitor)
library(rsample)
library(rstanarm)
library(tidymodels)
```

```{r clean 2020 noncompliance data}
issued_nc_2020 <- read_excel("raw_data/20200408_Issued Noncompliance_DHCD6_511266.xlsx") %>%
  clean_names() 

enrollment <- read_excel("raw_data/20200408_DHCD Enrollment_Data_DHCD6_511263.xlsx") %>%
  clean_names()

enrollment %>%
  group_by(termination_reason) %>%
  summarize(number = n()) %>% 
  arrange(desc(number)) 

unique(enrollment$termination_reason)

family_shelter_exit_data <- read_excel("raw_data/20200408_EA_Family_Shelter_Exit_Information_DHCD6_511139.xlsx") %>%
  clean_names() %>%
  rename(housing_subsidies = what_type_s_of_housing_subsidies_were_used_for_this_placement_select_all_that_apply_1135) %>%
  separate(housing_subsidies, into = c("subsidy_1", "subsidy_2", "subsidy_3", "subsidy_4"), sep = "\\|", fill = 'right')

unique(family_shelter_exit_data$subsidy_1)
unique(family_shelter_exit_data$subsidy_2)
unique(family_shelter_exit_data$subsidy_3)
unique(family_shelter_exit_data$subsidy_4)
unique(family_shelter_exit_data$is_new_address_available_2372)

family_shelter_exit_data %>%
  pivot_longer(cols = c(subsidy_1, subsidy_2, subsidy_3), 
               names_to = "subsidy",  
               values_to = "subsidy_type") %>%
  drop_na(subsidy_type) %>%
  filter(subsidy_type != "") %>%
  group_by(subsidy_type) %>%
  summarize(num_subsidy = n()) %>% 
  arrange(desc(num_subsidy)) 

exit_data <- read_excel("raw_data/20200408_Exit_DHCD6_511249.xlsx") %>%
  clean_names()

unique(exit_data$destination) %>% sort()

exit_data %>%
  mutate(destination = recode(destination, 
                             `1` = "shelter",
                             `2` = "transitional housing program",
                             `3` = "permanent housing for formerly homeless persons",
                             `4` = "psychiatric facility",
                             `5` = "substance abuse treatment program",
                             `6` = "hospital or other non-psych medical facility",
                             `7` = "jail/prison",
                             `8` = "client doesn’t know",
                             `9` = "client refused",
                             `10` = "rental by client, no ongoing subsidy",
                             `11` = "owned by client, no ongoing subsidy",
                             `12` = "temporarily staying with family",
                             `13` = "temporarily staying with friends",
                             `14` = "hotel/motel without emergency shelter voucher",
                             `15` = "foster care/foster group home",
                             `16` = "place not meant for human habitation",
                             `17` = "other – defined by HMIS as not a positive outcome",
                             `18` = "safe haven",
                             `19` = "rental by client with VASH housing subsidy",
                             `20` = "rental by client with other ongoing housing subsidy",
                             `21` = "owned by client with ongoing subsidy",
                             `22` = "permanently staying with family",
                             `23` = "permanently staying with friends",
                             `24` = "deceased",
                             `25` = "long-term care facility/nursing home",
                             `26` = "moved from HOPWA to HOPWA PH",
                             `27` = "moved from HOPWA to HOPWA TH",
                             `28` = "rental by client with GPD TIP subsidy – VA-funded Grant Per Diem Transition in Place",
                             `29` = "residential/halfway house with no homeless criteria",
                             `30` = "no exit interview completed",
                             `31` = "rental by client with rapid rehousing or equivalent",
                             `33` = "rental by client with Section 8",
                             `34` = "rental by client in public housing",
                             `33` = "rental by client with Section 8",
                             `99` = "data not collected")) %>%
  group_by(destination) %>%
  summarize(number = n()) %>% 
  arrange(desc(number)) 

unique(exit_data$housing_assessment %>% sort())

exit_data %>%
  mutate(housing_assessment = recode(housing_assessment, 
                             `1` = "able to maintain the housing they had at project entry",
                             `2` = "moved to new housing unit",
                             `3` = "moved in with family/friends on temporary basis",
                             `4` = "moved in with family/friends on permanent basis",
                             `5` = "moved to transitional/temporary housing facility/program",
                             `6` = "homeless – shelter or place not meant for human habitation",
                             `9` = "client refused",
                             `99` = "data not collected",
                              )) %>%
  group_by(housing_assessment) %>%
  summarize(number = n()) %>% 
  arrange(desc(number)) 

unique(exit_data$subsidy_information %>% sort())

exit_data %>%
  group_by(subsidy_information) %>%
  summarize(number = n()) %>% 
  arrange(desc(number)) 

hud_exit_data_2020 <- read_excel("raw_data/20200408_HUD Exit_Data_with_Termination Reason_DHCD6_511260.xlsx") %>%
  clean_names()

unique(hud_exit_data_2020$destination %>% sort())
unique(hud_exit_data_2020$housing_assessment %>% sort())
unique(hud_exit_data_2020$subsidy_information)
unique(hud_exit_data_2020$termination_reason %>% sort())

hud_exit_data_2020 %>%
  group_by(termination_reason) %>%
  summarize(number = n()) %>% 
  arrange(desc(number)) 

hud_exit_data_2020 %>%
  select(exit_date) %>%
  arrange(exit_date)
```

```{r clean 2018 noncompliance data}
issued_nc_2018 <- read_excel("raw_data/10_NonCompliance_TPs.xlsx") %>%
  clean_names() %>%
  rename(pei = participant_enterprise_identifier,
         date_nc = date_of_incident_2497,
         notice_type = type_of_notice_issued_2500,
         violation_type = what_type_of_violation_2712) %>%
  select(pei, date_nc, notice_type, violation_type) %>%
  
  # Eliminate hyphens from the PEI identification number.
    
  mutate(pei = gsub("-", "", pei)) %>%
  
  # No more than 3 violations are provided to any one row. So, I divide the
  # violation_type column into three columns, based on the "\\|" divider. 
  # Missing values are filled on the right.
    
  separate(violation_type, into = c("violation_1", "violation_2", "violation_3"), sep = "\\|", fill = 'right') %>%
  mutate(violation_1 = na_if(violation_1,""),
         violation_2 = na_if(violation_2,""),
         violation_3 = na_if(violation_3,""))
```

```{r merge noncompliance data}
issued_nc_2020 <- read_excel("raw_data/20200408_Issued Noncompliance_DHCD6_511266.xlsx") %>%
  clean_names() %>%
  rename(pei = participant_enterprise_identifier,
         date_nc = date_of_incident,
         notice_type = type_of_notice_issued_2500,
         violation_type = what_type_of_violation_2712) %>%
  select(pei, date_nc, notice_type, violation_type) %>%
  
  # Eliminate hyphens from the PEI identification number.
    
  mutate(pei = gsub("-", "", pei)) %>%
  
  # No more than 3 violations are provided to any one row. So, I divide the
  # violation_type column into three columns, based on the "\\|" divider. 
  # Missing values are filled on the right.
    
  separate(violation_type, into = c("violation_1", "violation_2", "violation_3"), sep = "\\|", fill = 'right') %>%
  mutate(violation_1 = na_if(violation_1,""),
         violation_2 = na_if(violation_2,""),
         violation_3 = na_if(violation_3,""))

issued_ncs <- bind_rows(issued_nc_2020, issued_nc_2018) %>%
  arrange(date_nc) %>%
  rename(nc_notice_type = notice_type,
         nc_violation_1 = violation_1,
         nc_violation_2 = violation_2,
         nc_violation_3 = violation_3)

write_csv(issued_ncs, 
          path = "/Users/monicachang/Documents*/gbls/project/Garcia-vs-DHCD/processed_data/issued_ncs.csv")
```

```{r clean 2018 and 2020 hud exit data}

hud_exit_data_2018 <- read_excel("raw_data/20181220_HUD_Exit_Data_with_Termination Reason.xlsx") %>%
  clean_names() %>%
  rename(pei = personal_id,
         date_exit = exit_date) %>%
  
  # Eliminate hyphens from the PEI identification number.
    
  mutate(pei = gsub("-", "", pei)) %>%
  
  # I recode the destination codes so they are more interpretable.

  mutate(destination = recode(destination, 
                             `1` = "shelter",
                             `2` = "transitional housing program",
                             `3` = "permanent housing for formerly homeless persons",
                             `4` = "psychiatric facility",
                             `5` = "substance abuse treatment program",
                             `6` = "hospital or other non-psych medical facility",
                             `7` = "jail/prison",
                             `8` = "client doesn’t know",
                             `9` = "client refused",
                             `10` = "rental by client, no ongoing subsidy",
                             `11` = "owned by client, no ongoing subsidy",
                             `12` = "temporarily staying with family",
                             `13` = "temporarily staying with friends",
                             `14` = "hotel/motel without emergency shelter voucher",
                             `15` = "foster care/foster group home",
                             `16` = "place not meant for human habitation",
                             `17` = "other – defined by HMIS as not a positive outcome",
                             `18` = "safe haven",
                             `19` = "rental by client with VASH housing subsidy",
                             `20` = "rental by client with other ongoing housing subsidy",
                             `21` = "owned by client with ongoing subsidy",
                             `22` = "permanently staying with family",
                             `23` = "permanently staying with friends",
                             `24` = "deceased",
                             `25` = "long-term care facility/nursing home",
                             `26` = "moved from HOPWA to HOPWA PH",
                             `27` = "moved from HOPWA to HOPWA TH",
                             `28` = "rental by client with GPD TIP subsidy – VA-funded Grant Per Diem Transition in Place",
                             `29` = "residential/halfway house with no homeless criteria",
                             `30` = "no exit interview completed",
                             `31` = "rental by client with rapid rehousing or equivalent",
                             `33` = "rental by client with Section 8",
                             `34` = "rental by client in public housing",
                             `33` = "rental by client with Section 8",
                             `99` = "data not collected")) %>%
  mutate(termination_reason = recode(termination_reason, 
                             `Feasible ALT Housing w/ HB Household Assistance` = "Feasible Alt Housing w/ HB Household Assistance",
                             `Feasible ALT Housing w/o HB Household Assistance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `Feasible Alt Housing w/ Household Assistance` = "Feasible Alt Housing w/ HB Household Assistance",
                             `Abandon of Shelter Plmnt/2 Consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Abandon of Shelter Plmnt/2consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Abandonment of Shelter Placement` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Feasible ALT w/o HB Household Assistance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `Feasible ALT Housing w/o HB Household Assitance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `2nd Noncompliance: Threat health and safety` = "2nd Noncompliance: Threat to health and safety",
                             `Abandon Shelter Plmnt/2 Consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Feasible ALT HSG: Other (inc needs not met)` = "Feasible ALT HSG: Other (inc needs not being met)",
                             `Feasible ALT HSG - Other (inc needs not being met)` = "Feasible ALT HSG: Other (inc needs not being met)")) %>%
  select(pei, date_exit, destination, termination_reason)

hud_exit_data_2018 %>%
  group_by(termination_reason) %>%
  summarize(number = n()) %>% 
  arrange(desc(number))

hud_exit_data_2020 <- read_excel("raw_data/20200408_HUD Exit_Data_with_Termination Reason_DHCD6_511260.xlsx") %>%
  clean_names() %>%
  rename(pei = personal_id,
         date_exit = exit_date) %>%
  
  # Eliminate hyphens from the PEI identification number.
    
  mutate(pei = gsub("-", "", pei)) %>%
  
  # I recode the destination codes so they are more interpretable.

  mutate(destination = recode(destination, 
                             `1` = "shelter",
                             `2` = "transitional housing program",
                             `3` = "permanent housing for formerly homeless persons",
                             `4` = "psychiatric facility",
                             `5` = "substance abuse treatment program",
                             `6` = "hospital or other non-psych medical facility",
                             `7` = "jail/prison",
                             `8` = "client doesn’t know",
                             `9` = "client refused",
                             `10` = "rental by client, no ongoing subsidy",
                             `11` = "owned by client, no ongoing subsidy",
                             `12` = "temporarily staying with family",
                             `13` = "temporarily staying with friends",
                             `14` = "hotel/motel without emergency shelter voucher",
                             `15` = "foster care/foster group home",
                             `16` = "place not meant for human habitation",
                             `17` = "other – defined by HMIS as not a positive outcome",
                             `18` = "safe haven",
                             `19` = "rental by client with VASH housing subsidy",
                             `20` = "rental by client with other ongoing housing subsidy",
                             `21` = "owned by client with ongoing subsidy",
                             `22` = "permanently staying with family",
                             `23` = "permanently staying with friends",
                             `24` = "deceased",
                             `25` = "long-term care facility/nursing home",
                             `26` = "moved from HOPWA to HOPWA PH",
                             `27` = "moved from HOPWA to HOPWA TH",
                             `28` = "rental by client with GPD TIP subsidy – VA-funded Grant Per Diem Transition in Place",
                             `29` = "residential/halfway house with no homeless criteria",
                             `30` = "no exit interview completed",
                             `31` = "rental by client with rapid rehousing or equivalent",
                             `33` = "rental by client with Section 8",
                             `34` = "rental by client in public housing",
                             `33` = "rental by client with Section 8",
                             `99` = "data not collected")) %>%
  mutate(termination_reason = recode(termination_reason, 
                             `Feasible ALT Housing w/ HB Household Assistance` = "Feasible Alt Housing w/ HB Household Assistance",
                             `Feasible ALT Housing w/o HB Household Assistance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `Feasible Alt Housing w/ Household Assistance` = "Feasible Alt Housing w/ HB Household Assistance",
                             `Abandon of Shelter Plmnt/2 Consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Abandon of Shelter Plmnt/2consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Abandonment of Shelter Placement` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Feasible ALT w/o HB Household Assistance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `Feasible ALT Housing w/o HB Household Assitance` = "Feasible Alt Housing w/o HB Household Assistance",
                             `2nd Noncompliance: Threat health and safety` = "2nd Noncompliance: Threat to health and safety",
                             `Abandon Shelter Plmnt/2 Consecutive NA overngts` = "Abandon of Shelter Plmnt/2 consecutive NA overngts",
                             `Feasible ALT HSG: Other (inc needs not met)` = "Feasible ALT HSG: Other (inc needs not being met)",
                             `Feasible ALT HSG - Other (inc needs not being met)` = "Feasible ALT HSG: Other (inc needs not being met)")) %>%
  select(pei, date_exit, destination, termination_reason)

hud_exit_data_2020 %>%
  group_by(termination_reason) %>%
  summarize(number = n()) %>% 
  arrange(desc(number))

hud_exit_data <- bind_rows(hud_exit_data_2020, hud_exit_data_2018) %>%
  arrange(date_exit) %>%
  rename(exit_destination = destination,
         exit_reason = termination_reason)

write_csv(hud_exit_data, 
          path = "/Users/monicachang/Documents*/gbls/project/Garcia-vs-DHCD/processed_data/hud_exit_data.csv")
```

```{r merge ada and noncompliance data}
supplemented_unit_type_ada_transfers_t <- read_csv(file = "/Users/monicachang/Documents*/gbls/project/Garcia-vs-DHCD/processed_data/supplemented_unit_type_ada_transfers_t.csv")
                      
# I use a left join because I want to keep all of the rows from my 
# supplemented_unit_type_ada_transfers_t tibble - even if there is no 
# corresponding non-compliance information.This merge will allow me to see 
# whether the individual received a non-compliance during their wait for
# disability accommodation.

# 138/609 individuals approved for scattered site, first floor, or wheelchair
# access were issued a non-compliance at any point.

# 86/105 of those individuals had a noncompliance after they applied for 
# disability accommodation.

# 19/72 of those individuals had a noncompliance after they applied for 
# disability accommodation AND before they received accommodation.

ada_ncs <- left_join(supplemented_unit_type_ada_transfers_t, issued_ncs, by = "pei") %>%
  select(pei, name, date_received, date_decision, date_nc, date_referral, date_acc_met, days_until_accommodation_met)

# This table only contains the date of the first noncompliance (if it exists)
# for any individual.

ada_ncs_first <- ada_ncs %>%
  
  # I filter to only keep dates of noncompliance if they occurred after the
  # individual applied for disability accommodation.
  
  mutate(date_nc = if_else(is.na(date_nc), date_nc, if_else(date_nc > date_received, date_nc, as.POSIXct(NA)))) %>%
 
  # Group the data by each unique pei-date_received combo.
  
  group_by(pei, date_received) %>%
  
  # Keep the earliest issued noncompliance after the individual applied for 
  # disability accommodation (if it exists).
  
  arrange(date_nc) %>%
  slice(1)
  
ada_ncs_interesting <- ada_ncs %>%
  filter(!is.na(date_nc)) %>%
  filter(date_nc >= date_received & date_nc <= date_acc_met) %>%
  select(pei, name, date_received, date_decision, date_nc, date_referral, date_acc_met, days_until_accommodation_met)
```

```{r merge ada and exit data}
hud_data <- read_csv(file = "/Users/monicachang/Documents*/gbls/project/Garcia-vs-DHCD/processed_data/hud_exit_data.csv") %>%
  filter(exit_destination != "shelter" | is.na(exit_destination)) 

# ASK: Should I keep "transferred" exit outcomes if they aren't transferred to shelter?

hud_tesi_data <- hud_data %>%
  filter(exit_reason == "Temporary Emergency Shelter Interruption") %>%
  rename(date_tesi = date_exit) %>%
  select(pei, date_tesi)

hud_exit_data <- hud_data %>%
  filter(exit_reason != "Temporary Emergency Shelter Interruption")

hud_exit_data %>%
  filter(exit_reason == "Transferred") %>%
  group_by(exit_destination) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) 

hud_exit_data %>%
  group_by(exit_reason) %>%
  summarize(n = n()) %>%
  arrange(desc(n)) 
                      
# I use a left join because I want to keep all of the rows from my 
# ada_ncs tibble - even if there is no corresponding exit information.
# This merge will allow me to see what kind of exit outcome the individual 
# received.

ada_ncs_tesi <- left_join(ada_ncs_first, hud_tesi_data, by = "pei") %>%
  select(pei, name, date_received, date_decision, date_referral, date_acc_met, days_until_accommodation_met, date_nc, date_tesi)

ada_ncs_tesi_first <- ada_ncs_tesi %>%
  
  # I filter to only keep dates of TESI if they occurred after the
  # individual applied for disability accommodation.
  
  mutate(date_tesi = if_else(is.na(date_tesi), date_tesi, if_else(date_tesi > date_received, date_tesi, as.POSIXct(NA)))) %>%
 
  # Group the data by each unique pei-date_received combo.
  
  group_by(pei, date_received) %>%
  
  # Keep the earliest issued TESI after the individual applied for 
  # disability accommodation (if it exists).
  
  arrange(date_tesi) %>%
  slice(1)
  
ada_ncs_tesi_exit <- left_join(ada_ncs_tesi_first, hud_exit_data, by = "pei") %>%
  select(pei, name, date_received, date_decision, date_referral, date_acc_met, days_until_accommodation_met, date_nc, date_tesi, date_exit, exit_reason) 

ada_ncs_tesi_exit_first <- ada_ncs_tesi_exit %>%
  
  # I filter to only keep dates of exit if they occurred after 
  # the individual applied for disability accommodation.

  mutate(date_exit = if_else(is.na(date_exit), date_exit, if_else(date_exit > date_received, date_exit, as.POSIXct(NA)))) %>%
 
  # Group the data by each unique pei-date_received combo.
  
  group_by(pei, date_received) %>%
  
  # Keep the earliest exit after the individual applied for 
  # disability accommodation (if it exists).
  
  arrange(date_exit) %>%
  slice(1)

ada_ncs_tesi_exit_final <- ada_ncs_tesi_exit_first %>%
    mutate(date_referral = as.Date(date_referral),
           date_nc = as.Date(date_nc),
           date_tesi = as.Date(date_tesi),
           date_exit = as.Date(date_exit)) %>%
    mutate(last_followup = date_received) %>%
    mutate(last_followup = if_else(!is.na(date_decision) & date_decision > last_followup, date_decision, last_followup)) %>%
    mutate(last_followup = if_else(!is.na(date_referral) & date_referral > last_followup, date_referral, last_followup)) %>%
    mutate(last_followup = if_else(!is.na(date_acc_met) & date_acc_met > last_followup, date_acc_met, last_followup)) %>%
    mutate(last_followup = if_else(!is.na(date_nc) & date_nc > last_followup, date_nc, last_followup)) %>%
    mutate(last_followup = if_else(!is.na(date_tesi) & date_tesi > last_followup, date_tesi, last_followup)) %>%
    mutate(last_followup = if_else(!is.na(date_exit) & date_exit > last_followup, date_exit, last_followup)) 

write_csv(ada_ncs_tesi_exit_final, 
          path = "/Users/monicachang/Documents*/gbls/project/Garcia-vs-DHCD/processed_data/ada_ncs_tesi_exit_final.csv")

# 439/609 individuals approved for scattered site, first floor, or wheelchair
# access had an exit outcome at any point.

# 402/439 of those individuals had an exit outcome after they applied for 
# disability accommodation.

# 64/402 of those individuals had an exit outcome after they applied for 
# disability accommodation AND before they received accommodation. How is
# this possible?

ada_ncs_tesi_exit_interesting <- ada_ncs_tesi_exit %>%
  filter(!is.na(date_exit)) %>%
  filter(date_exit >= date_received) %>%
  select(pei, name, date_received, date_decision, date_nc, date_referral, date_acc_met, days_until_accommodation_met, date_exit)

```